<Ngap_AdditionalDLUPTNLInformationForHOItem.h>
<Ngap_AdditionalDLUPTNLInformationForHOList.h>
<Ngap_AdditionalQosFlowInformation.h>
<Ngap_AllocationAndRetentionPriority.h>
<Ngap_AllowedNSSAI.h>
<Ngap_AllowedNSSAI-Item.h>
<Ngap_AllowedTACs.h>
<Ngap_AMFConfigurationUpdateAcknowledge.h>
<Ngap_AMFConfigurationUpdateFailure.h>
<Ngap_AMFConfigurationUpdate.h>
<Ngap_AMFName.h>
<Ngap_AMFPagingTarget.h>
<Ngap_AMFPointer.h>
<Ngap_AMFRegionID.h>
<Ngap_AMFSetID.h>
<Ngap_AMFStatusIndication.h>
<Ngap_AMF-TNLAssociationSetupItem.h>
<Ngap_AMF-TNLAssociationSetupList.h>
<Ngap_AMF-TNLAssociationToAddItem.h>
<Ngap_AMF-TNLAssociationToAddList.h>
<Ngap_AMF-TNLAssociationToRemoveItem.h>
<Ngap_AMF-TNLAssociationToRemoveList.h>
<Ngap_AMF-TNLAssociationToUpdateItem.h>
<Ngap_AMF-TNLAssociationToUpdateList.h>
<Ngap_AMF-UE-NGAP-ID.h>
<Ngap_AreaOfInterestCellItem.h>
<Ngap_AreaOfInterestCellList.h>
<Ngap_AreaOfInterest.h>
<Ngap_AreaOfInterestItem.h>
<Ngap_AreaOfInterestList.h>
<Ngap_AreaOfInterestRANNodeItem.h>
<Ngap_AreaOfInterestRANNodeList.h>
<Ngap_AreaOfInterestTAIItem.h>
<Ngap_AreaOfInterestTAIList.h>
<Ngap_AssistanceDataForPaging.h>
<Ngap_AssistanceDataForRecommendedCells.h>
<Ngap_AssociatedQosFlowItem.h>
<Ngap_AssociatedQosFlowList.h>
<Ngap_AveragingWindow.h>
<Ngap_BitRate.h>
<Ngap_BroadcastCancelledAreaList.h>
<Ngap_BroadcastCompletedAreaList.h>
<Ngap_BroadcastPLMNItem.h>
<Ngap_BroadcastPLMNList.h>
<Ngap_CancelAllWarningMessages.h>
<Ngap_CancelledCellsInEAI-EUTRA.h>
<Ngap_CancelledCellsInEAI-EUTRA-Item.h>
<Ngap_CancelledCellsInEAI-NR.h>
<Ngap_CancelledCellsInEAI-NR-Item.h>
<Ngap_CancelledCellsInTAI-EUTRA.h>
<Ngap_CancelledCellsInTAI-EUTRA-Item.h>
<Ngap_CancelledCellsInTAI-NR.h>
<Ngap_CancelledCellsInTAI-NR-Item.h>
<Ngap_Cause.h>
<Ngap_CauseMisc.h>
<Ngap_CauseNas.h>
<Ngap_CauseProtocol.h>
<Ngap_CauseRadioNetwork.h>
<Ngap_CauseTransport.h>
<Ngap_CellIDBroadcastEUTRA.h>
<Ngap_CellIDBroadcastEUTRA-Item.h>
<Ngap_CellIDBroadcastNR.h>
<Ngap_CellIDBroadcastNR-Item.h>
<Ngap_CellIDCancelledEUTRA.h>
<Ngap_CellIDCancelledEUTRA-Item.h>
<Ngap_CellIDCancelledNR.h>
<Ngap_CellIDCancelledNR-Item.h>
<Ngap_CellIDListForRestart.h>
<Ngap_CellSize.h>
<Ngap_CellTrafficTrace.h>
<Ngap_CellType.h>
<Ngap_CompletedCellsInEAI-EUTRA.h>
<Ngap_CompletedCellsInEAI-EUTRA-Item.h>
<Ngap_CompletedCellsInEAI-NR.h>
<Ngap_CompletedCellsInEAI-NR-Item.h>
<Ngap_CompletedCellsInTAI-EUTRA.h>
<Ngap_CompletedCellsInTAI-EUTRA-Item.h>
<Ngap_CompletedCellsInTAI-NR.h>
<Ngap_CompletedCellsInTAI-NR-Item.h>
<Ngap_ConcurrentWarningMessageInd.h>
<Ngap_ConfidentialityProtectionIndication.h>
<Ngap_ConfidentialityProtectionResult.h>
<Ngap_CoreNetworkAssistanceInformation.h>
<Ngap_COUNTValueForPDCP-SN12.h>
<Ngap_COUNTValueForPDCP-SN18.h>
<Ngap_CPTransportLayerInformation.h>
<Ngap_CriticalityDiagnostics.h>
<Ngap_CriticalityDiagnostics-IE-Item.h>
<Ngap_CriticalityDiagnostics-IE-List.h>
<Ngap_Criticality.h>
<Ngap_DataCodingScheme.h>
<Ngap_DataForwardingAccepted.h>
<Ngap_DataForwardingNotPossible.h>
<Ngap_DataForwardingResponseDRBItem.h>
<Ngap_DataForwardingResponseDRBList.h>
<Ngap_DeactivateTrace.h>
<Ngap_DelayCritical.h>
<Ngap_DirectForwardingPathAvailability.h>
<Ngap_DLForwarding.h>
<Ngap_DL-NGU-TNLInformationReused.h>
<Ngap_DownlinkNASTransport.h>
<Ngap_DownlinkNonUEAssociatedNRPPaTransport.h>
<Ngap_DownlinkRANConfigurationTransfer.h>
<Ngap_DownlinkRANStatusTransfer.h>
<Ngap_DownlinkUEAssociatedNRPPaTransport.h>
<Ngap_DRB-ID.h>
<Ngap_DRBsSubjectToStatusTransferItem.h>
<Ngap_DRBsSubjectToStatusTransferList.h>
<Ngap_DRBStatusDL12.h>
<Ngap_DRBStatusDL18.h>
<Ngap_DRBStatusDL.h>
<Ngap_DRBStatusUL12.h>
<Ngap_DRBStatusUL18.h>
<Ngap_DRBStatusUL.h>
<Ngap_DRBsToQosFlowsMappingItem.h>
<Ngap_DRBsToQosFlowsMappingList.h>
<Ngap_Dynamic5QIDescriptor.h>
<Ngap_EmergencyAreaIDBroadcastEUTRA.h>
<Ngap_EmergencyAreaIDBroadcastEUTRA-Item.h>
<Ngap_EmergencyAreaIDBroadcastNR.h>
<Ngap_EmergencyAreaIDBroadcastNR-Item.h>
<Ngap_EmergencyAreaIDCancelledEUTRA.h>
<Ngap_EmergencyAreaIDCancelledEUTRA-Item.h>
<Ngap_EmergencyAreaIDCancelledNR.h>
<Ngap_EmergencyAreaIDCancelledNR-Item.h>
<Ngap_EmergencyAreaID.h>
<Ngap_EmergencyAreaIDListForRestart.h>
<Ngap_EmergencyAreaIDList.h>
<Ngap_EmergencyFallbackIndicator.h>
<Ngap_EmergencyFallbackRequestIndicator.h>
<Ngap_EmergencyServiceTargetCN.h>
<Ngap_EN-DCSONConfigurationTransfer.h>
<Ngap_EPS-TAC.h>
<Ngap_EPS-TAI.h>
<Ngap_EquivalentPLMNs.h>
<Ngap_E-RAB-ID.h>
<Ngap_E-RABInformationItem.h>
<Ngap_E-RABInformationList.h>
<Ngap_ErrorIndication.h>
<Ngap_EUTRACellIdentity.h>
<Ngap_EUTRA-CGI.h>
<Ngap_EUTRA-CGIListForWarning.h>
<Ngap_EUTRA-CGIList.h>
<Ngap_EUTRAencryptionAlgorithms.h>
<Ngap_EUTRAintegrityProtectionAlgorithms.h>
<Ngap_EventType.h>
<Ngap_ExpectedActivityPeriod.h>
<Ngap_ExpectedHOInterval.h>
<Ngap_ExpectedIdlePeriod.h>
<Ngap_ExpectedUEActivityBehaviour.h>
<Ngap_ExpectedUEBehaviour.h>
<Ngap_ExpectedUEMobility.h>
<Ngap_ExpectedUEMovingTrajectory.h>
<Ngap_ExpectedUEMovingTrajectoryItem.h>
<Ngap_FiveG-S-TMSI.h>
<Ngap_FiveG-TMSI.h>
<Ngap_FiveQI.h>
<Ngap_ForbiddenAreaInformation.h>
<Ngap_ForbiddenAreaInformation-Item.h>
<Ngap_ForbiddenTACs.h>
<Ngap_GBR-QosInformation.h>
<Ngap_GlobalGNB-ID.h>
<Ngap_GlobalN3IWF-ID.h>
<Ngap_GlobalNgENB-ID.h>
<Ngap_GlobalRANNodeID.h>
<Ngap_GNB-ID.h>
<Ngap_GTP-TEID.h>
<Ngap_GTPTunnel.h>
<Ngap_GUAMI.h>
<Ngap_HandoverCancelAcknowledge.h>
<Ngap_HandoverCancel.h>
<Ngap_HandoverCommand.h>
<Ngap_HandoverCommandTransfer.h>
<Ngap_HandoverFailure.h>
<Ngap_HandoverFlag.h>
<Ngap_HandoverNotify.h>
<Ngap_HandoverPreparationFailure.h>
<Ngap_HandoverPreparationUnsuccessfulTransfer.h>
<Ngap_HandoverRequestAcknowledge.h>
<Ngap_HandoverRequestAcknowledgeTransfer.h>
<Ngap_HandoverRequest.h>
<Ngap_HandoverRequired.h>
<Ngap_HandoverRequiredTransfer.h>
<Ngap_HandoverResourceAllocationUnsuccessfulTransfer.h>
<Ngap_HandoverType.h>
<Ngap_IMSVoiceSupportIndicator.h>
<Ngap_IndexToRFSP.h>
<Ngap_InfoOnRecommendedCellsAndRANNodesForPaging.h>
<Ngap_InitialContextSetupFailure.h>
<Ngap_InitialContextSetupRequest.h>
<Ngap_InitialContextSetupResponse.h>
<Ngap_InitialUEMessage.h>
<Ngap_InitiatingMessage.h>
<Ngap_IntegrityProtectionIndication.h>
<Ngap_IntegrityProtectionResult.h>
<Ngap_IntendedNumberOfPagingAttempts.h>
<Ngap_InterfacesToTrace.h>
<Ngap_LastVisitedCellInformation.h>
<Ngap_LastVisitedCellItem.h>
<Ngap_LastVisitedEUTRANCellInformation.h>
<Ngap_LastVisitedGERANCellInformation.h>
<Ngap_LastVisitedNGRANCellInformation.h>
<Ngap_LastVisitedUTRANCellInformation.h>
<Ngap_LocationReport.h>
<Ngap_LocationReportingControl.h>
<Ngap_LocationReportingFailureIndication.h>
<Ngap_LocationReportingReferenceID.h>
<Ngap_LocationReportingRequestType.h>
<Ngap_MaskedIMEISV.h>
<Ngap_MaximumDataBurstVolume.h>
<Ngap_MaximumIntegrityProtectedDataRate.h>
<Ngap_MessageIdentifier.h>
<Ngap_MICOModeIndication.h>
<Ngap_MobilityRestrictionList.h>
<Ngap_N3IWF-ID.h>
<Ngap_NASNonDeliveryIndication.h>
<Ngap_NAS-PDU.h>
<Ngap_NASSecurityParametersFromNGRAN.h>
<Ngap_NetworkInstance.h>
<Ngap_NewSecurityContextInd.h>
<Ngap_NextHopChainingCount.h>
<Ngap_NextPagingAreaScope.h>
<Ngap_NGAP-PDU.h>
<Ngap_NgENB-ID.h>
<Ngap_NGRAN-CGI.h>
<Ngap_NGRANTraceID.h>
<Ngap_NGResetAcknowledge.h>
<Ngap_NGReset.h>
<Ngap_NGSetupFailure.h>
<Ngap_NGSetupRequest.h>
<Ngap_NGSetupResponse.h>
<Ngap_NonDynamic5QIDescriptor.h>
<Ngap_NotAllowedTACs.h>
<Ngap_NotificationCause.h>
<Ngap_NotificationControl.h>
<Ngap_NRCellIdentity.h>
<Ngap_NR-CGI.h>
<Ngap_NR-CGIListForWarning.h>
<Ngap_NR-CGIList.h>
<Ngap_NRencryptionAlgorithms.h>
<Ngap_NRintegrityProtectionAlgorithms.h>
<Ngap_NRPPa-PDU.h>
<Ngap_NumberOfBroadcasts.h>
<Ngap_NumberOfBroadcastsRequested.h>
<Ngap_OverloadAction.h>
<Ngap_OverloadResponse.h>
<Ngap_OverloadStart.h>
<Ngap_OverloadStartNSSAIItem.h>
<Ngap_OverloadStartNSSAIList.h>
<Ngap_OverloadStop.h>
<Ngap_PacketDelayBudget.h>
<Ngap_PacketErrorRate.h>
<Ngap_PacketLossRate.h>
<Ngap_PagingAttemptCount.h>
<Ngap_PagingAttemptInformation.h>
<Ngap_PagingDRX.h>
<Ngap_Paging.h>
<Ngap_PagingOrigin.h>
<Ngap_PagingPriority.h>
<Ngap_PathSwitchRequestAcknowledge.h>
<Ngap_PathSwitchRequestAcknowledgeTransfer.h>
<Ngap_PathSwitchRequestFailure.h>
<Ngap_PathSwitchRequest.h>
<Ngap_PathSwitchRequestSetupFailedTransfer.h>
<Ngap_PathSwitchRequestTransfer.h>
<Ngap_PathSwitchRequestUnsuccessfulTransfer.h>
<Ngap_PDUSessionAggregateMaximumBitRate.h>
<Ngap_PDUSessionID.h>
<Ngap_PDUSessionResourceAdmittedItem.h>
<Ngap_PDUSessionResourceAdmittedList.h>
<Ngap_PDUSessionResourceFailedToModifyItemModCfm.h>
<Ngap_PDUSessionResourceFailedToModifyItemModRes.h>
<Ngap_PDUSessionResourceFailedToModifyListModCfm.h>
<Ngap_PDUSessionResourceFailedToModifyListModRes.h>
<Ngap_PDUSessionResourceFailedToSetupItemCxtFail.h>
<Ngap_PDUSessionResourceFailedToSetupItemCxtRes.h>
<Ngap_PDUSessionResourceFailedToSetupItemHOAck.h>
<Ngap_PDUSessionResourceFailedToSetupItemPSReq.h>
<Ngap_PDUSessionResourceFailedToSetupItemSURes.h>
<Ngap_PDUSessionResourceFailedToSetupListCxtFail.h>
<Ngap_PDUSessionResourceFailedToSetupListCxtRes.h>
<Ngap_PDUSessionResourceFailedToSetupListHOAck.h>
<Ngap_PDUSessionResourceFailedToSetupListPSReq.h>
<Ngap_PDUSessionResourceFailedToSetupListSURes.h>
<Ngap_PDUSessionResourceHandoverItem.h>
<Ngap_PDUSessionResourceHandoverList.h>
<Ngap_PDUSessionResourceInformationItem.h>
<Ngap_PDUSessionResourceInformationList.h>
<Ngap_PDUSessionResourceItemCxtRelCpl.h>
<Ngap_PDUSessionResourceItemCxtRelReq.h>
<Ngap_PDUSessionResourceItemHORqd.h>
<Ngap_PDUSessionResourceListCxtRelCpl.h>
<Ngap_PDUSessionResourceListCxtRelReq.h>
<Ngap_PDUSessionResourceListHORqd.h>
<Ngap_PDUSessionResourceModifyConfirm.h>
<Ngap_PDUSessionResourceModifyConfirmTransfer.h>
<Ngap_PDUSessionResourceModifyIndication.h>
<Ngap_PDUSessionResourceModifyIndicationTransfer.h>
<Ngap_PDUSessionResourceModifyIndicationUnsuccessfulTransfer.h>
<Ngap_PDUSessionResourceModifyItemModCfm.h>
<Ngap_PDUSessionResourceModifyItemModInd.h>
<Ngap_PDUSessionResourceModifyItemModReq.h>
<Ngap_PDUSessionResourceModifyItemModRes.h>
<Ngap_PDUSessionResourceModifyListModCfm.h>
<Ngap_PDUSessionResourceModifyListModInd.h>
<Ngap_PDUSessionResourceModifyListModReq.h>
<Ngap_PDUSessionResourceModifyListModRes.h>
<Ngap_PDUSessionResourceModifyRequest.h>
<Ngap_PDUSessionResourceModifyRequestTransfer.h>
<Ngap_PDUSessionResourceModifyResponse.h>
<Ngap_PDUSessionResourceModifyResponseTransfer.h>
<Ngap_PDUSessionResourceModifyUnsuccessfulTransfer.h>
<Ngap_PDUSessionResourceNotify.h>
<Ngap_PDUSessionResourceNotifyItem.h>
<Ngap_PDUSessionResourceNotifyList.h>
<Ngap_PDUSessionResourceNotifyReleasedTransfer.h>
<Ngap_PDUSessionResourceNotifyTransfer.h>
<Ngap_PDUSessionResourceReleaseCommand.h>
<Ngap_PDUSessionResourceReleaseCommandTransfer.h>
<Ngap_PDUSessionResourceReleasedItemNot.h>
<Ngap_PDUSessionResourceReleasedItemPSAck.h>
<Ngap_PDUSessionResourceReleasedItemPSFail.h>
<Ngap_PDUSessionResourceReleasedItemRelRes.h>
<Ngap_PDUSessionResourceReleasedListNot.h>
<Ngap_PDUSessionResourceReleasedListPSAck.h>
<Ngap_PDUSessionResourceReleasedListPSFail.h>
<Ngap_PDUSessionResourceReleasedListRelRes.h>
<Ngap_PDUSessionResourceReleaseResponse.h>
<Ngap_PDUSessionResourceReleaseResponseTransfer.h>
<Ngap_PDUSessionResourceSecondaryRATUsageItem.h>
<Ngap_PDUSessionResourceSecondaryRATUsageList.h>
<Ngap_PDUSessionResourceSetupItemCxtReq.h>
<Ngap_PDUSessionResourceSetupItemCxtRes.h>
<Ngap_PDUSessionResourceSetupItemHOReq.h>
<Ngap_PDUSessionResourceSetupItemSUReq.h>
<Ngap_PDUSessionResourceSetupItemSURes.h>
<Ngap_PDUSessionResourceSetupListCxtReq.h>
<Ngap_PDUSessionResourceSetupListCxtRes.h>
<Ngap_PDUSessionResourceSetupListHOReq.h>
<Ngap_PDUSessionResourceSetupListSUReq.h>
<Ngap_PDUSessionResourceSetupListSURes.h>
<Ngap_PDUSessionResourceSetupRequest.h>
<Ngap_PDUSessionResourceSetupRequestTransfer.h>
<Ngap_PDUSessionResourceSetupResponse.h>
<Ngap_PDUSessionResourceSetupResponseTransfer.h>
<Ngap_PDUSessionResourceSetupUnsuccessfulTransfer.h>
<Ngap_PDUSessionResourceSwitchedItem.h>
<Ngap_PDUSessionResourceSwitchedList.h>
<Ngap_PDUSessionResourceToBeSwitchedDLItem.h>
<Ngap_PDUSessionResourceToBeSwitchedDLList.h>
<Ngap_PDUSessionResourceToReleaseItemHOCmd.h>
<Ngap_PDUSessionResourceToReleaseItemRelCmd.h>
<Ngap_PDUSessionResourceToReleaseListHOCmd.h>
<Ngap_PDUSessionResourceToReleaseListRelCmd.h>
<Ngap_PDUSessionType.h>
<Ngap_PDUSessionUsageReport.h>
<Ngap_PeriodicRegistrationUpdateTimer.h>
<Ngap_PLMNIdentity.h>
<Ngap_PLMNSupportItem.h>
<Ngap_PLMNSupportList.h>
<Ngap_PortNumber.h>
<Ngap_Pre-emptionCapability.h>
<Ngap_Pre-emptionVulnerability.h>
<Ngap_Presence.h>
<Ngap_PriorityLevelARP.h>
<Ngap_PriorityLevelQos.h>
<Ngap_PrivateIE-Container.h>
<Ngap_PrivateIE-Field.h>
<Ngap_PrivateIE-ID.h>
<Ngap_PrivateMessage.h>
<Ngap_ProcedureCode.h>
<Ngap_ProtocolExtensionContainer.h>
<Ngap_ProtocolExtensionField.h>
<Ngap_ProtocolExtensionID.h>
<Ngap_ProtocolIE-Container.h>
<Ngap_ProtocolIE-ContainerList.h>
<Ngap_ProtocolIE-ContainerPair.h>
<Ngap_ProtocolIE-ContainerPairList.h>
<Ngap_ProtocolIE-Field.h>
<Ngap_ProtocolIE-FieldPair.h>
<Ngap_ProtocolIE-ID.h>
<Ngap_ProtocolIE-SingleContainer.h>
<Ngap_PWSCancelRequest.h>
<Ngap_PWSCancelResponse.h>
<Ngap_PWSFailedCellIDList.h>
<Ngap_PWSFailureIndication.h>
<Ngap_PWSRestartIndication.h>
<Ngap_QosCharacteristics.h>
<Ngap_QosFlowAcceptedItem.h>
<Ngap_QosFlowAcceptedList.h>
<Ngap_QosFlowAddOrModifyRequestItem.h>
<Ngap_QosFlowAddOrModifyRequestList.h>
<Ngap_QosFlowAddOrModifyResponseItem.h>
<Ngap_QosFlowAddOrModifyResponseList.h>
<Ngap_QosFlowIdentifier.h>
<Ngap_QosFlowInformationItem.h>
<Ngap_QosFlowInformationList.h>
<Ngap_QosFlowItemWithDataForwarding.h>
<Ngap_QosFlowLevelQosParameters.h>
<Ngap_QosFlowListWithCause.h>
<Ngap_QosFlowListWithDataForwarding.h>
<Ngap_QosFlowModifyConfirmItem.h>
<Ngap_QosFlowModifyConfirmList.h>
<Ngap_QosFlowNotifyItem.h>
<Ngap_QosFlowNotifyList.h>
<Ngap_QosFlowPerTNLInformation.h>
<Ngap_QosFlowPerTNLInformationItem.h>
<Ngap_QosFlowPerTNLInformationList.h>
<Ngap_QosFlowSetupRequestItem.h>
<Ngap_QosFlowSetupRequestList.h>
<Ngap_QosFlowSetupResponseItemSURes.h>
<Ngap_QosFlowSetupResponseListSURes.h>
<Ngap_QoSFlowsUsageReport-Item.h>
<Ngap_QoSFlowsUsageReportList.h>
<Ngap_QosFlowToBeForwardedItem.h>
<Ngap_QosFlowToBeForwardedList.h>
<Ngap_QosFlowWithCauseItem.h>
<Ngap_RANConfigurationUpdateAcknowledge.h>
<Ngap_RANConfigurationUpdateFailure.h>
<Ngap_RANConfigurationUpdate.h>
<Ngap_RANNodeName.h>
<Ngap_RANPagingPriority.h>
<Ngap_RANStatusTransfer-TransparentContainer.h>
<Ngap_RAN-UE-NGAP-ID.h>
<Ngap_RATRestrictionInformation.h>
<Ngap_RATRestrictions.h>
<Ngap_RATRestrictions-Item.h>
<Ngap_RecommendedCellItem.h>
<Ngap_RecommendedCellList.h>
<Ngap_RecommendedCellsForPaging.h>
<Ngap_RecommendedRANNodeItem.h>
<Ngap_RecommendedRANNodeList.h>
<Ngap_RecommendedRANNodesForPaging.h>
<Ngap_RedirectionVoiceFallback.h>
<Ngap_ReferenceID.h>
<Ngap_ReflectiveQosAttribute.h>
<Ngap_RelativeAMFCapacity.h>
<Ngap_RepetitionPeriod.h>
<Ngap_ReportArea.h>
<Ngap_RerouteNASRequest.h>
<Ngap_ResetAll.h>
<Ngap_ResetType.h>
<Ngap_RoutingID.h>
<Ngap_RRCContainer.h>
<Ngap_RRCEstablishmentCause.h>
<Ngap_RRCInactiveTransitionReport.h>
<Ngap_RRCInactiveTransitionReportRequest.h>
<Ngap_RRCState.h>
<Ngap_SD.h>
<Ngap_SecondaryRATDataUsageReport.h>
<Ngap_SecondaryRATDataUsageReportTransfer.h>
<Ngap_SecondaryRATUsageInformation.h>
<Ngap_SecurityContext.h>
<Ngap_SecurityIndication.h>
<Ngap_SecurityKey.h>
<Ngap_SecurityResult.h>
<Ngap_SerialNumber.h>
<Ngap_ServedGUAMIItem.h>
<Ngap_ServedGUAMIList.h>
<Ngap_ServiceAreaInformation.h>
<Ngap_ServiceAreaInformation-Item.h>
<Ngap_SliceOverloadItem.h>
<Ngap_SliceOverloadList.h>
<Ngap_SliceSupportItem.h>
<Ngap_SliceSupportList.h>
<Ngap_S-NSSAI.h>
<Ngap_SONConfigurationTransfer.h>
<Ngap_SONInformation.h>
<Ngap_SONInformationReply.h>
<Ngap_SONInformationRequest.h>
<Ngap_SourceNGRANNode-ToTargetNGRANNode-TransparentContainer.h>
<Ngap_SourceOfUEActivityBehaviourInformation.h>
<Ngap_SourceRANNodeID.h>
<Ngap_SourceToTarget-TransparentContainer.h>
<Ngap_SST.h>
<Ngap_SuccessfulOutcome.h>
<Ngap_SupportedTAItem.h>
<Ngap_SupportedTAList.h>
<Ngap_TAC.h>
<Ngap_TAIBroadcastEUTRA.h>
<Ngap_TAIBroadcastEUTRA-Item.h>
<Ngap_TAIBroadcastNR.h>
<Ngap_TAIBroadcastNR-Item.h>
<Ngap_TAICancelledEUTRA.h>
<Ngap_TAICancelledEUTRA-Item.h>
<Ngap_TAICancelledNR.h>
<Ngap_TAICancelledNR-Item.h>
<Ngap_TAI.h>
<Ngap_TAIListForInactive.h>
<Ngap_TAIListForInactiveItem.h>
<Ngap_TAIListForPaging.h>
<Ngap_TAIListForPagingItem.h>
<Ngap_TAIListForRestart.h>
<Ngap_TAIListForWarning.h>
<Ngap_TargeteNB-ID.h>
<Ngap_TargetID.h>
<Ngap_TargetNGRANNode-ToSourceNGRANNode-TransparentContainer.h>
<Ngap_TargetRANNodeID.h>
<Ngap_TargetToSource-TransparentContainer.h>
<Ngap_TimerApproachForGUAMIRemoval.h>
<Ngap_TimeStamp.h>
<Ngap_TimeToWait.h>
<Ngap_TimeUEStayedInCellEnhancedGranularity.h>
<Ngap_TimeUEStayedInCell.h>
<Ngap_TNLAddressWeightFactor.h>
<Ngap_TNLAssociationItem.h>
<Ngap_TNLAssociationList.h>
<Ngap_TNLAssociationUsage.h>
<Ngap_TraceActivation.h>
<Ngap_TraceDepth.h>
<Ngap_TraceFailureIndication.h>
<Ngap_TraceStart.h>
<Ngap_TrafficLoadReductionIndication.h>
<Ngap_TransportLayerAddress.h>
<Ngap_TriggeringMessage.h>
<Ngap_TypeOfError.h>
<Ngap_UEAggregateMaximumBitRate.h>
<Ngap_UE-associatedLogicalNG-connectionItem.h>
<Ngap_UE-associatedLogicalNG-connectionList.h>
<Ngap_UEContextModificationFailure.h>
<Ngap_UEContextModificationRequest.h>
<Ngap_UEContextModificationResponse.h>
<Ngap_UEContextReleaseCommand.h>
<Ngap_UEContextReleaseComplete.h>
<Ngap_UEContextReleaseRequest.h>
<Ngap_UEContextRequest.h>
<Ngap_UEHistoryInformation.h>
<Ngap_UEIdentityIndexValue.h>
<Ngap_UE-NGAP-ID-pair.h>
<Ngap_UE-NGAP-IDs.h>
<Ngap_UEPagingIdentity.h>
<Ngap_UEPresence.h>
<Ngap_UEPresenceInAreaOfInterestItem.h>
<Ngap_UEPresenceInAreaOfInterestList.h>
<Ngap_UERadioCapabilityCheckRequest.h>
<Ngap_UERadioCapabilityCheckResponse.h>
<Ngap_UERadioCapabilityForPaging.h>
<Ngap_UERadioCapabilityForPagingOfEUTRA.h>
<Ngap_UERadioCapabilityForPagingOfNR.h>
<Ngap_UERadioCapability.h>
<Ngap_UERadioCapabilityInfoIndication.h>
<Ngap_UERetentionInformation.h>
<Ngap_UESecurityCapabilities.h>
<Ngap_UETNLABindingReleaseRequest.h>
<Ngap_UL-NGU-UP-TNLModifyItem.h>
<Ngap_UL-NGU-UP-TNLModifyList.h>
<Ngap_UnavailableGUAMIItem.h>
<Ngap_UnavailableGUAMIList.h>
<Ngap_UnsuccessfulOutcome.h>
<Ngap_UplinkNASTransport.h>
<Ngap_UplinkNonUEAssociatedNRPPaTransport.h>
<Ngap_UplinkRANConfigurationTransfer.h>
<Ngap_UplinkRANStatusTransfer.h>
<Ngap_UplinkUEAssociatedNRPPaTransport.h>
<Ngap_UPTransportLayerInformation.h>
<Ngap_UPTransportLayerInformationItem.h>
<Ngap_UPTransportLayerInformationList.h>
<Ngap_UPTransportLayerInformationPairItem.h>
<Ngap_UPTransportLayerInformationPairList.h>
<Ngap_UserLocationInformationEUTRA.h>
<Ngap_UserLocationInformation.h>
<Ngap_UserLocationInformationN3IWF.h>
<Ngap_UserLocationInformationNR.h>
<Ngap_UserPlaneSecurityInformation.h>
<Ngap_VolumeTimedReport-Item.h>
<Ngap_VolumeTimedReportList.h>
<Ngap_WarningAreaCoordinates.h>
<Ngap_WarningAreaList.h>
<Ngap_WarningMessageContents.h>
<Ngap_WarningSecurityInfo.h>
<Ngap_WarningType.h>
<Ngap_WriteReplaceWarningRequest.h>
<Ngap_WriteReplaceWarningResponse.h>
<Ngap_XnExtTLA-Item.h>
<Ngap_XnExtTLAs.h>
<Ngap_XnGTP-TLAs.h>
<Ngap_XnTLAs.h>
<Ngap_XnTNLConfigurationInfo.h>
